#!/usr/bin/env bash
# install.sh - Meeting Recorder Linux installer (Fedora 43 / COSMIC)
set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
APP_DIR="$HOME/Applications/MeetingGui"
DATA_DIR="$HOME/.local/share/meeting-recorder"
DESKTOP_DIR="$HOME/.local/share/applications"
AUTOSTART_DIR="$HOME/.config/autostart"

echo "=== Meeting Recorder Linux Installer ==="

# 1. System dependencies
echo "[1/6] Checking system dependencies..."
if ! python3 -c "import gi" &>/dev/null; then
    echo "  Installing GTK4 Python bindings..."
    sudo dnf install -y python3-gobject gtk4 || {
        echo "ERROR: Could not install GTK4. Install manually: sudo dnf install python3-gobject gtk4"
        exit 1
    }
fi

# 2. Python dependencies
echo "[2/6] Installing Python dependencies..."
pip install --user -r "$SCRIPT_DIR/requirements.txt"

# 3. App directory
echo "[3/6] Setting up app directory..."
mkdir -p "$APP_DIR"
mkdir -p "$DATA_DIR/pending"
cp "$SCRIPT_DIR/meeting_gui.py" "$APP_DIR/"

# 4. Environment file
echo "[4/6] Configuring environment..."
if [ ! -f "$APP_DIR/.env" ]; then
    cp "$SCRIPT_DIR/../.env.example" "$APP_DIR/.env"
    echo "  Created $APP_DIR/.env -- fill in your API keys before running."
else
    echo "  .env already exists, skipping."
fi

# 5. Launch script
echo "[5/6] Writing launch script..."
cat > "$APP_DIR/meeting_recorder_launch.sh" << EOF
#!/usr/bin/env bash
# Auto-generated by install.sh
set -a
source "\$(dirname "\$0")/.env"
set +a
exec python3 "\$(dirname "\$0")/meeting_gui.py" "\$@"
EOF
chmod +x "$APP_DIR/meeting_recorder_launch.sh"

# 6. Desktop file
echo "[6/6] Installing desktop entry..."
mkdir -p "$DESKTOP_DIR"
cat > "$DESKTOP_DIR/meeting-recorder.desktop" << EOF
[Desktop Entry]
Name=Meeting Recorder
Comment=AI-powered meeting recorder and transcription
Exec=$APP_DIR/meeting_recorder_launch.sh
Icon=audio-input-microphone
Terminal=false
Type=Application
Categories=Utility;AudioVideo;
StartupWMClass=com.fractionalmedtech.meeting-recorder
EOF
update-desktop-database "$DESKTOP_DIR" 2>/dev/null || true

echo ""
echo "=== Installation complete ==="
echo "Next: Edit $APP_DIR/.env and add your API keys."
echo "Then launch via: $APP_DIR/meeting_recorder_launch.sh"
echo "Or find 'Meeting Recorder' in your app launcher."
